import assert from 'node:assert/strict';
import { getControlLesson, getTeaRestoration, normalizeProgress, settleProgress, nextRelic, MAX_HEALTH, RETURN_WINDOW, TERRAIN } from '../src/lantern/model.ts';
import { createBrain, stepEnemy, strikeDamage } from '../src/lantern/combat.ts';
import { stepHorizontalCamera } from '../src/lantern/camera.ts';

const fresh = normalizeProgress(null);
assert.equal(fresh.returns, 0);
assert.equal(fresh.weapon, 'blade');
assert.equal(fresh.controlsVisible, true);
assert.deepEqual(fresh.learnedControls, []);
assert.equal(normalizeProgress({ controlsVisible: false }).controlsVisible, false);
assert.deepEqual(normalizeProgress({ learnedControls: ['move', 'unknown', 'move', 'jump'] }).learnedControls, ['move', 'jump']);
assert.equal(normalizeProgress({ returns: 0, weapon: 'feather' }).weapon, 'blade');
assert.deepEqual(normalizeProgress({ relics: ['bell', 'bell', 'unknown'] }).relics, ['bell']);
assert.equal(normalizeProgress({ returns: -3, attempts: Infinity }).attempts, 0);
assert.equal(normalizeProgress({ bestTimeMs: NaN }).bestTimeMs, null);
const lost = settleProgress(fresh, { outcome: 'lost', relic: 'bell', durationMs: 1000 });
assert.deepEqual(lost, fresh);
const won = settleProgress(fresh, { outcome: 'won', relic: 'bell', durationMs: 65_000 });
assert.equal(won.returns, 1);
assert.deepEqual(won.relics, ['bell']);
assert.equal(nextRelic(won), 'letter');
assert.equal(settleProgress(won, { outcome: 'won', relic: 'bell', durationMs: 70_000 }).bestTimeMs, 65_000);
assert.equal(normalizeProgress({ ...won, weapon: 'feather' }).weapon, 'feather');
const guard = createBrain({ id: 'guard', kind: 'guard', x: 400, floor: 700 });
stepEnemy(guard, { x: 300, y: 675 }, 1000);
assert.equal(guard.phase, 'windup');
assert.equal(strikeDamage(guard, 300, false, false), 0);
assert.equal(strikeDamage(guard, 450, false, false), 1);
assert.equal(strikeDamage(guard, 300, false, true), 1);
const charged = stepEnemy(guard, { x: 700, y: 675 }, 1700);
assert.equal(guard.phase, 'strike');
assert(charged.vx < 0, 'A telegraphed charge must not track a dodge behind the guard.');
stepEnemy(guard, { x: 700, y: 675 }, 2100);
assert.equal(guard.phase, 'recover');
assert.equal(strikeDamage(guard, 300, false, false), 2);
assert.equal(strikeDamage(guard, 300, true, false), 3);
const keeper = createBrain({ id: 'keeper', kind: 'keeper', x: 400, floor: 620 });
assert.equal(strikeDamage(keeper, 450, true, false), 0);
assert.equal(strikeDamage(keeper, 450, true, true), 1);
keeper.phase = 'recover';
assert.equal(strikeDamage(keeper, 450, true, false), 3);
assert.equal(MAX_HEALTH, 6);
assert.equal(RETURN_WINDOW, 120_000);
assert(TERRAIN.every((tile) => tile.width > 0 && tile.height > 0));
assert.deepEqual(getTeaRestoration(6, false, 120_000), { healthGained: 0, lightGained: 0 });
assert.deepEqual(getTeaRestoration(4, false, 120_000), { healthGained: 2, lightGained: 0 });
assert.deepEqual(getTeaRestoration(5, false, 120_000), { healthGained: 1, lightGained: 0 });
assert.deepEqual(getTeaRestoration(6, true, 98_000), { healthGained: 0, lightGained: 10_000 });
assert.deepEqual(getTeaRestoration(6, true, 119_800), { healthGained: 0, lightGained: 200 });
assert.deepEqual(getTeaRestoration(6, true, 120_000), { healthGained: 0, lightGained: 0 });
const guidance = { phase: 'home', learned: new Set(), x: 360, footY: 700, facing: 1, grounded: true, canInteract: false, enemyNearby: false, enemyWindingUp: false };
assert.equal(getControlLesson(guidance), 'move');
assert.equal(getControlLesson({ ...guidance, learned: new Set(['move']) }), 'attack');
const walking = { ...guidance, phase: 'outbound', learned: new Set(['move', 'attack']) };
assert.equal(getControlLesson({ ...walking, x: 1180 }), 'jump');
assert.equal(getControlLesson({ ...walking, x: 1180, learned: new Set() }), 'jump', 'A nearby obstacle takes precedence when replaying hints.');
assert.equal(getControlLesson({ ...walking, x: 800 }), null, 'Adjacent level ground must not trigger the jump cue.');
assert.equal(getControlLesson({ ...walking, x: 1180, grounded: false }), null);
assert.equal(getControlLesson({ ...walking, canInteract: true }), 'interact');
assert.equal(getControlLesson({ ...walking, enemyWindingUp: true }), 'dash');
assert.equal(getControlLesson({ ...walking, phase: 'won', canInteract: true }), null);
assert.equal(getControlLesson({ ...walking, x: 1180, learned: new Set(['move', 'attack', 'jump']) }), null);
let camera = { lookAhead: 0, lookTarget: 0, direction: 0, stableMs: 0, center: 2500 };
for (let frame = 0; frame < 120; frame++) {
  camera = stepHorizontalCamera(camera, camera.center, 2500, frame % 8 < 4 ? 325 : -325, 1100, 1000 / 60);
  assert.equal(camera.lookTarget, 0, 'Rapid direction changes should not move the look-ahead target.');
  assert.equal(camera.center, 2500);
}
let playerX = 2500;
let largestStep = 0;
for (let frame = 0; frame < 240; frame++) {
  const velocity = frame < 120 ? 325 : -325;
  playerX += velocity / 60;
  const previous = camera;
  camera = stepHorizontalCamera(camera, camera.center, playerX, velocity, 1100, 1000 / 60);
  largestStep = Math.max(largestStep, Math.abs(camera.center - previous.center));
  assert(Math.abs(camera.lookAhead - previous.lookAhead) < 2, 'Look-ahead reversed abruptly.');
}
assert(largestStep <= 8.001);
assert(camera.lookTarget < 0, 'Sustained travel should eventually change the look-ahead direction.');
console.log(JSON.stringify({ ok: true, progression: true, deathPreservesUnlocks: true, telegraphs: true, recoveryBonus: true, contextualGuidance: true, teaRestoration: true, cameraComfort: true }));
